### ISSUE TITLE
在本地安装上依赖之后  打包不出来呀

### ISSUE THREAD

**Issue by liuhao16** [imba97/Btools-vue#1]
在本地安装上依赖之后  打包不出来呀

**Comment by imba97** [comment]
我这里是没啥问题的，刚才重新clone了一遍跑了跑。
依赖安装完运行
```bash
npm run c
```
打包chrome版本（目前只有这个）

现在这个插件还没功能，只是个演示

**Comment by liuhao16** [comment]
我一会再试一下 可能是我操作有问题
