### ISSUE TITLE
前几天开始视频封面按钮没了

### ISSUE THREAD

**Issue by QuantumNingen** [imba97/Btools-vue#26]
似乎是B站更新了什么东西，当未登录时封面按钮还在，但登录后却没了，换了几个chrome内核的浏览器都是如此。

**Comment by imba97** [comment]
我好像没遇到，是普通视频么 还是番剧、电影

**Comment by QuantumNingen** [comment]
> 我好像没遇到，是普通视频么 还是番剧、电影

所有视频都是

**Comment by QuantumNingen** [comment]
> 我好像没遇到，是普通视频么 还是番剧、电影

我发现了，按钮不是没了，是位置跑到屏幕外面去了。
打开f12后
```
<div class="btools-get-pic-video" btools-bind-hkm-id="9c7mS1jz" ondragstart="return false;" style="top: 10px; left: -40px;">
```
会发现这一行末尾，" style="top: 10px; left: -40px;"这两个坐标有问题，同一个视频登录前还是top: 162px; left: 737.5px，这是正常的位置。登陆后所有视频都变成了10，-40这个奇怪的坐标，手动改数值能暂时让按钮回来。

**Comment by imba97** [comment]
按说这个按钮位置是根据视频播放器定位的，而且好像是监听页面大小实时调整位置的，有可能是播放器`id`或者`class`换了

**Comment by imba97** [comment]
> 



> > 我好像没遇到，是普通视频么 还是番剧、电影
> 
> 我发现了，按钮不是没了，是位置跑到屏幕外面去了。 打开f12后
> 
> ```
> <div class="btools-get-pic-video" btools-bind-hkm-id="9c7mS1jz" ondragstart="return false;" style="top: 10px; left: -40px;">
> ```
> 
> 会发现这一行末尾，" style="top: 10px; left: -40px;"这两个坐标有问题，同一个视频登录前还是top: 162px; left: 737.5px，这是正常的位置。登陆后所有视频都变成了10，-40这个奇怪的坐标，手动改数值能暂时让按钮回来。

emmm，试了一下，我这里是能正常定位的，会根据页面大小定位到播放器左侧
目前不太清楚你那边是啥情况，没法复现

**Comment by QuantumNingen** [comment]
> > 
> 
> > > 我好像没遇到，是普通视频么 还是番剧、电影
> > 
> > 
> > 我发现了，按钮不是没了，是位置跑到屏幕外面去了。 打开f12后
> > ```
> > <div class="btools-get-pic-video" btools-bind-hkm-id="9c7mS1jz" ondragstart="return false;" style="top: 10px; left: -40px;">
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 会发现这一行末尾，" style="top: 10px; left: -40px;"这两个坐标有问题，同一个视频登录前还是top: 162px; left: 737.5px，这是正常的位置。登陆后所有视频都变成了10，-40这个奇怪的坐标，手动改数值能暂时让按钮回来。
> 
> emmm，试了一下，我这里是能正常定位的，会根据页面大小定位到播放器左侧 目前不太清楚你那边是啥情况，没法复现

10，-40这个坐标刚好差不多是正常显示的时候相对于视频左上角的坐标，但是变成了相对于整个页面左上角的坐标。我又试了下firefox，还是这样，未登录时是正常的，一登录就跑到屏幕外去了。

**Comment by imba97** [comment]
> 10，-40这个坐标刚好差不多是正常显示的时候相对于视频左上角的坐标，但是变成了相对于整个页面左上角的坐标。我又试了下firefox，还是这样，未登录时是正常的，一登录就跑到屏幕外去了。

可能改了什么东西在灰度测试，因为我这里目前还是正常的，再等等吧，正式发布了我这边再改

**Comment by QuantumNingen** [comment]
> > 10，-40这个坐标刚好差不多是正常显示的时候相对于视频左上角的坐标，但是变成了相对于整个页面左上角的坐标。我又试了下firefox，还是这样，未登录时是正常的，一登录就跑到屏幕外去了。
> 
> 可能改了什么东西在灰度测试，因为我这里目前还是正常的，再等等吧，正式发布了我这边再改

感觉有可能是B站的问题，因为现在有新版和旧版两种不同的视频页面。我用有的浏览器在未登录时是新版页面，封面按钮也是正常的。但用有的浏览器即使退出登录也无法在视频页面用新版，只有首页能切换新版。而所有浏览器登录后都无法在视频页面用新版。说明新版页面并没有推送给所有人，也许还在测试。我猜是这个造成的。

**Comment by QuantumNingen** [comment]
> > 10，-40这个坐标刚好差不多是正常显示的时候相对于视频左上角的坐标，但是变成了相对于整个页面左上角的坐标。我又试了下firefox，还是这样，未登录时是正常的，一登录就跑到屏幕外去了。
> 
> 可能改了什么东西在灰度测试，因为我这里目前还是正常的，再等等吧，正式发布了我这边再改

今天恢复正常了，应该是B站的播放页也正式改成新版了。
