### ISSUE TITLE
新版界面的评论区找不到选择表情按钮了，只有最近使用的表情

### ISSUE THREAD

**Issue by jiut** [imba97/Btools-vue#27]
![](https://s2.loli.net/2022/04/22/6lyd9sOfEgvTW2x.png)

**Comment by imba97** [comment]
emmm 感觉不像是插件的问题，我这里是有的
![image](https://user-images.githubusercontent.com/10150208/164649893-5ac7e4bd-66a6-4fe2-adb7-73bab5b4d01c.png)

你可以试试关掉插件刷新一下页面，看看有没有。如果关掉就有那是插件的问题

**Comment by jiut** [comment]
好的，确实是有的。

**Comment by imba97** [comment]
火狐的新版是输入框展开后才会显示
至于位置目前显示不正确的问题，后面会解决

![image](https://user-images.githubusercontent.com/10150208/164650618-6a84980f-0699-451d-ad89-0c5e6ecd485a.png)
